name: Code Formatter
on: [push, workflow_dispatch]
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for Showstoppers
        run: >
          autopep8 --verbose --in-place --recursive --aggressive --aggressive
          --ignore=W605 bot/modules/ bot/helpers/ bot/__init__.py
      - name: Remove Unused Imports and Variables
        run: >
          autoflake --in-place --recursive --remove-all-unused-imports
          --remove-unused-variables --ignore-init-module-imports .
      - name: Lint with Isort and Black
        run: |
          isort bot/modules/ bot/helpers/ bot/__init__.py
          black bot/modules/ bot/helpers/ bot/__init__.py
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Auto: Code Formatted"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: Ms Emily
          commit_user_email: emilymiss2022@gmail.com
          commit_author: MsEmily <emilymiss2022@gmail.com>
