name: Code Formatter
on: [push, workflow_dispatch]
jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
      - name: Install Python lint libraries
        run: |
          pip install autopep8 autoflake isort black
      - name: Check for Showstoppers
        run: >
          autopep8 --verbose --in-place --recursive --aggressive --aggressive
          --ignore=W605 bot/helpers/ bot/modules/ bot/plugins/developer bot/plugins/sudo bot/plugins/users bot/__init__.py bot/config.py bot/logging.py bot/version.py
      - name: Remove Unused Imports and Variables
        run: >
          autoflake --in-place --recursive --remove-all-unused-imports
          --remove-unused-variables --ignore-init-module-imports .
      - name: Lint with Isort and Black
        run: |
          isort bot/helpers/ bot/modules/ bot/plugins/developer bot/plugins/sudo bot/plugins/users bot/__init__.py bot/config.py bot/logging.py bot/version.py
          black bot/helpers/ bot/modules/ bot/plugins/developer bot/plugins/sudo bot/plugins/users bot/__init__.py bot/config.py bot/logging.py bot/version.py
      - uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: "Auto: Code Formatted"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: Ms Emily
          commit_user_email: emilymiss2022@gmail.com
          commit_author: MsEmily <emilymiss2022@gmail.com>
